/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthProviders {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  password_changed_at: Timestamp | null;
  password_hash: string | null;
  provider_data: Json | null;
  provider_type: string;
  provider_user_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  device_info: Json | null;
  expires_at: Timestamp;
  id: Generated<number>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_id: number;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string | null;
  email_verification_expires_at: Timestamp | null;
  email_verification_token: string | null;
  email_verified: Generated<boolean>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  password_reset_expires_at: Timestamp | null;
  password_reset_token: string | null;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  auth_providers: AuthProviders;
  refresh_tokens: RefreshTokens;
  users: Users;
}
